In [1]:
import pandas as pd
import numpy as np

In [43]:
df = pd.read_csv('./data/athlete_events.csv')
region_df = pd.read_csv('./data/noc_regions.csv')

In [3]:
df.head(2)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN

In [4]:
df.shape

(271116, 15)

In [5]:
region_df.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [6]:
df = df.merge(region_df, how="left",left_on="NOC",right_on="NOC")

In [7]:
df.head(5)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Netherlands,NaN

In [8]:
df['region'].unique()

array(['China', 'Denmark', 'Netherlands', 'USA', 'Finland', 'Norway',
       'Romania', 'Estonia', 'France', 'Morocco', 'Spain', 'Egypt',
       'Iran', 'Bulgaria', 'Italy', 'Chad', 'Azerbaijan', 'Sudan',
       'Russia', 'Argentina', 'Cuba', 'Belarus', 'Greece', 'Cameroon',
       'Turkey', 'Chile', 'Mexico', 'Nicaragua', 'Hungary', 'Nigeria',
       'Algeria', 'Kuwait', 'Bahrain', 'Pakistan', 'Iraq', 'Syria',
       'Lebanon', 'Qatar', 'Malaysia', 'Germany', 'Canada', 'Ireland',
       'Australia', 'South Africa', 'Eritrea', 'Tanzania', 'Jordan',
       'Tunisia', 'Libya', 'Belgium', 'Djibouti', 'Palestine', 'Comoros',
       'Kazakhstan', 'Brunei', 'India', 'Saudi Arabia', 'Maldives',
       'Ethiopia', 'United Arab Emirates', 'Yemen', 'Indonesia',
       'Philippines', nan, 'Uzbekistan', 'Kyrgyzstan', 'Tajikistan',
       'Japan', 'Republic of Congo', 'Switzerland', 'Brazil', 'Monaco',
       'Israel', 'Uruguay', 'Sweden', 'Virgin Islands, US', 'Sri Lanka',
       'Armenia', 'Ivory Coast', 'Kenya', 'Benin', 'Ukraine', 'UK',
       'Ghana', 'Somalia', 'Latvia', 'Niger', 'Mali', 'Afghanistan',
       'Poland', 'Costa Rica', 'Panama', 'Georgia', 'Slovenia', 'Croatia',
       'Guyana', 'New Zealand', 'Portugal', 'Paraguay', 'Angola',
       'Venezuela', 'Colombia', 'Bangladesh', 'Peru', 'El Salvador',
       'Puerto Rico', 'Uganda', 'Honduras', 'Ecuador', 'Turkmenistan',
       'Mauritius', 'Seychelles', 'Czech Republic', 'Luxembourg',
       'Mauritania', 'Saint Kitts', 'Trinidad', 'Dominican Republic',
       'Saint Vincent', 'Jamaica', 'Liberia', 'Suriname', 'Nepal',
       'Mongolia', 'Austria', 'Palau', 'Lithuania', 'Togo', 'Namibia',
       'Curacao', 'Iceland', 'American Samoa', 'Samoa', 'Rwanda',
       'Dominica', 'Haiti', 'Malta', 'Cyprus', 'Guinea', 'Belize',
       'South Korea', 'Thailand', 'Bermuda', 'Serbia', 'Sierra Leone',
       'Papua New Guinea', 'Individual Olympic Athletes', 'Oman', 'Fiji',
       'Vanuatu', 'Moldova', 'Bahamas', 'Guatemala',
       'Virgin Islands, British', 'Mozambique',
       'Central African Republic', 'Madagascar', 'Bosnia and Herzegovina',
       'Guam', 'Cayman Islands', 'Slovakia', 'Barbados', 'Guinea-Bissau',
       'Timor-Leste', 'Democratic Republic of the Congo', 'Gabon',
       'San Marino', 'Laos', 'Botswana', 'Cambodia', 'North Korea',
       'Solomon Islands', 'Senegal', 'Cape Verde', 'Equatorial Guinea',
       'Boliva', 'Andorra', 'Antigua', 'Zimbabwe', 'Grenada',
       'Saint Lucia', 'Micronesia', 'Myanmar', 'Malawi', 'Zambia',
       'Taiwan', 'Sao Tome and Principe', 'Macedonia', 'Tonga',
       'Liechtenstein', 'Montenegro', 'Gambia', 'Cook Islands', 'Albania',
       'Swaziland', 'Burkina Faso', 'Burundi', 'Aruba', 'Nauru',
       'Vietnam', 'Bhutan', 'Marshall Islands', 'Kiribati', 'Kosovo',
       'South Sudan', 'Lesotho'], dtype=object)

In [9]:
df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     231333
region       370
notes     266077
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(1385)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df['Medal'].value_counts()

Medal
Gold      13369
Bronze    13295
Silver    13108
Name: count, dtype: int64

In [13]:
df.shape

(269731, 17)

In [14]:
pd.get_dummies(df['Medal']).astype(int)

        Bronze  Gold  Silver
0            0     0       0
1            0     0       0
2            0     0       0
3            0     1       0
4            0     0       0
...        ...   ...     ...
271111       0     0       0
271112       0     0       0
271113       0     0       0
271114       0     0       0
271115       0     0       0

[269731 rows x 3 columns]

In [15]:
# concat these two horizontally to get the final dataframe
final_df = pd.concat([df,pd.get_dummies(df['Medal']).astype(int)],axis=1)

In [16]:
final_df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,0,0,0
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,0,0,0
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,0,0,0
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,0,1,0
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Netherlands,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN,Poland,NaN,0,0,0
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,Poland,NaN,0,0,0
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,Poland,NaN,0,0,0
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN,Poland,NaN,0,0,0
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN,Poland,NaN,0,0,0

In [36]:
final_df.groupby("NOC").sum()[["Gold","Silver","Bronze"]].reset_index().sort_values(by=["Gold","Silver","Bronze"], ascending=False)

     NOC  Gold  Silver  Bronze
216  USA  2638    1641    1358
214  URS  1082     732     689
79   GER   745     674     746
74   GBR   677     739     651
100  ITA   575     531     531
..   ...   ...     ...     ...
221  VIN     0       0       0
222  VNM     0       0       0
224  YAR     0       0       0
225  YEM     0       0       0
226  YMD     0       0       0

[230 rows x 4 columns]

In [37]:
final_df[(final_df["NOC"]=="IND") & (final_df["Year"] == 1928) & (final_df["Medal"] == "Gold")]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
4732,2699,Shaukat Ali,M,30.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
5032,2864,Richard James Allen,M,25.0,172.0,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
38352,19716,Dhyan Chand Bais,M,22.0,169.0,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
76886,39020,Michael Anthony Gateley,M,23.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
82144,41710,"William James ""Willie"" Goodsir-Cullen",M,21.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
89524,45360,Leslie Charles Hammond,M,23.0,184.0,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
116859,59150,"Feroz-ud-Din ""Feroze"" Khan",M,23.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
150463,75490,George Eric McCarthy Marthins,M,22.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
173081,86987,"Richard Alexander ""Rex"" Norris",M,28.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
189138,95008,Broome Eric Pinniger,M,25.0,180.0,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
202266,101590,Michael E. Rocque,M,NaN,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
215286,108082,Frederick Stephen Seaman,M,22.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
221073,111081,Jaipal Singh Munda,M,25.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
266934,133554,Sayed Muhammad Yusuf,M,NaN,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0

In [38]:
medal_tally = final_df.drop_duplicates(subset=["NOC","Year","Games","Medal","Season","City","Event","Sport"])

In [39]:
    medal_tally = medal_tally.groupby("NOC").sum()[["Gold","Silver","Bronze"]].sort_values(by=["Gold","Silver","Bronze"],ascending=False).reset_index()

In [42]:
medal_tally.head()

   NOC  Gold  Silver  Bronze
0  USA  1131     901     791
1  URS   471     373     353
2  GER   319     345     340
3  GBR   289     320     310
4  FRA   264     286     329

In [41]:
medal_tally[medal_tally["NOC"] == "IND"]

    NOC  Gold  Silver  Bronze
51  IND    10       7      12